# 实训日志

时间：2022.7.4 - 2022.7.10

姓名：朱焰星

班级：计科1901

学号：2019317220115

小组：第三组 —— 朱焰星

---

## 2022-7-4

阅读实验指导书，了解需要掌握的基础知识

确定实现功能的方法：使用三种基础方法 + resnet深度学习方法提取图像特征。GUI界面使用python自带的库函数tkinter

规划任务进度计划：前三天完成基础功能以及GUI，后三天进行深度学习的代码编写。

开始编写三种基础方法提取一张图像特征的代码

完成了特征提取以及数据库的构建，不同方法存放在不同的csv表格中

## 2022-7-5

完成了特征匹配的代码编写

开始编写GUI界面

完成了选择图片、选择数据库、提取特征三个功能的GUI实现。

## 2022-7-6

继续编写GUI

### Problem 1

遇到一个问题，在GUI界面使用Button的函数后，得到的数据想继续在主函数中处理，但是发现并不能得到返回的数据

解决思路：在功能函数中得到的数据，并不返回。而是继续处理，将tk的主要界面当作参数也传递给Button绑定的功能函数上面。

尝试后发现可行

### Problem 2

想要在GUI上显示选择的图片时遇到错误。

Image.open(path.get())
AttributeError: 'str' object has no attribute 'read'

> 因为第一行的from PIL import Image与第二行tkinter import *冲突，tkinter中也含有Image类，所以你使用的是tkinter.Image
>
> 解决方法：`from PIL import Image as imim`

尝试后发现不行

但是改成如下：img0 = Image.open("Pic/bk.jpg"), 可以成功

发现问题：path中的路径是需要选择图片之后才获得的路径，而直接写出来则会导致并没有点击Button选择图片代码就开始获取文本框中的数据，自然没有任何东西

尝试将图片展示放在Button(选择图片)的函数中

```python
#  选择图片
def img_choose(win, img_path):
    # 打开文件管理器，选择图片
    pic_path = filedialog.askopenfilename(parent=win, initialdir=os.getcwd(), title="本地上传")
    # 将图片路径写入文本框内
    # img_path.delete(0,"end")
    img_path.insert(0, pic_path)
    # 图片显示
    search_img = img_resize(1182, 665, Image.open(pic_path))
    img0 = ImageTk.PhotoImage(search_img)
    lb0 = tk.Label(win, imag=img0, compound=tk.CENTER)
    lb0.place(relx=0.65, rely=0.1, relwidth=0.3, relheight=0.3)
```

发现仍然报错

```
(CBIR) star@StardeMacBook-Air CBIR1 % python Main_win.py
Traceback (most recent call last):
  File "/Users/star/miniconda3/envs/CBIR/lib/python3.10/site-packages/PIL/Image.py", line 3072, in open
    fp.seek(0)
AttributeError: 'str' object has no attribute 'seek'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/star/workspace/python/Image-Practice/CBIR1/Main_win.py", line 46, in <module>
    img0 = Image.open(str(path.get()))
  File "/Users/star/miniconda3/envs/CBIR/lib/python3.10/site-packages/PIL/Image.py", line 3074, in open
    fp = io.BytesIO(fp.read())
AttributeError: 'str' object has no attribute 'read'
(CBIR) star@StardeMacBook-Air CBIR1 % python Main_win.py
<PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=1080x1080 at 0x11BED7F40>
<PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=1305x602 at 0x11BED7EE0>
(CBIR) star@StardeMacBook-Air CBIR1 % python Main_win.py
<PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=1305x602 at 0x1202CFF40>
```

```
[ WARN:0@0.487] global /Users/xperience/actions-runner/_work/opencv-python/opencv-python/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_(''): can't open/read file: check file path/integrity
Traceback (most recent call last):
  File "/Users/star/workspace/python/Image-Practice/CBIR1/Main_win.py", line 41, in <module>
    fun_shape = tk.Button(win, text='Color', command=SearchAndSet(win, 0, path))
  File "/Users/star/workspace/python/Image-Practice/CBIR1/Main_fun.py", line 48, in SearchAndSet
    img_list = searchByColorMoment(img_path)
  File "/Users/star/workspace/python/Image-Practice/CBIR1/FeatureSelect.py", line 44, in searchByColorMoment
    features = list(np.array(color_moments(search_image)))
TypeError: iteration over a 0-d array
```

其中第一行的报错，指得是path中无法读取到任何东西，所以一定是之前的错误还没有解决。在没有点击Button时，就执行了函数，自然读取不到图片的路径。

进行改进：

```python
# 进行匹配
fun_color = tk.Button(win, text='Color', command=lambda: SearchAndSet(win, 0, path))
fun_color.place(relx=0.55, rely=0.05, relwidth=0.05, relheight=0.05)

fun_texture = tk.Button(win, text='Texture', command=lambda: SearchAndSet(win, 1, path))
fun_texture.place(relx=0.55, rely=0.11, relwidth=0.05, relheight=0.05)

fun_shape = tk.Button(win, text='Shape', command=lambda: SearchAndSet(win, 2, path))
fun_shape.place(relx=0.55, rely=0.17, relwidth=0.05, relheight=0.05)
```

发现代码停止抱错，但是在图片显示位置只有一个灰色的框。经过实验发现，在Button绑定的功能函数里加图片，则不能正常显示，在主函数里加图片，可以正常显示，效果如下：
<img src="https://s1.vika.cn/space/2022/07/06/9849f402f2c94eadb9ed1ef5f5a08124" alt="image-20220706151645421" style="zoom:30%;" />

实验代码如下：

```python
from PIL import Image
from PIL import ImageTk
import tkinter as tk

def fun(win):
    img0 = Image.open("Pic/bk.jpg")
    img0 = ImageTk.PhotoImage(img0)
    lb0 = tk.Label(win, imag=img0, compound=tk.CENTER)
    lb0.place(relx=0.1, rely=0.5, relwidth=0.3, relheight=0.3)

#  ==============   主界面   ================
win = tk.Tk()
win.geometry("1182x665")
win.title('基于内容的图像检索(CBIR)')

#  ==============   添加背景和标题   ================
background = tk.PhotoImage(file="Pic/duck.png")  # 背景图片
bg = tk.Label(win, image=background, compound=tk.CENTER, bg="#989cb8")
bg.place(relx=0, rely=0, relwidth=1, relheight=1)

img0 = Image.open("Pic/bk.jpg")
img0 = ImageTk.PhotoImage(img0)
lb0 = tk.Label(win, imag=img0, compound=tk.CENTER)
lb0.place(relx=0.1, rely=0.1, relwidth=0.3, relheight=0.3)

fun_color = tk.Button(win, text='Color', command=lambda: fun(win))
fun_color.place(relx=0.55, rely=0.05, relwidth=0.05, relheight=0.05)

win.mainloop()
```

通过剖析python的函数原理，得到了将ImageTk.PhotoImage()放在函数里图片不显示的原因：

- 在调用`fun()`函数后，**垃圾回收机制**会把变量`photo`给回收了。

- 解决办法：使用`global`全局变量。

  讲上述第6行开始的代码改为：

  ```python
  global img0
  img0 = Image.open("Pic/bk.jpg")
  img0 = ImageTk.PhotoImage(img0)
  ```

成功解决



### Problem 3

全部GUI编写完成进行测试的时候，提取特征步骤出现了之前未见到的报错：

```python
(CBIR) star@StardeMacBook-Air CBIR1 % python Main_win.py
/Users/star/workspace/python/Image-Practice/CBIR1/dataset
['.DS_Store', '101_ObjectCategories']
.DS_Store
Exception in Tkinter callback
Traceback (most recent call last):
  File "/Users/star/miniconda3/envs/CBIR/lib/python3.10/tkinter/__init__.py", line 1921, in __call__
    return self.func(*args)
  File "/Users/star/workspace/python/Image-Practice/CBIR1/Main_win.py", line 29, in <lambda>
    enter_setdb = tk.Button(win, text="提取特征", command=lambda: extract_feature(path))
  File "/Users/star/workspace/python/Image-Practice/CBIR1/Main_fun.py", line 45, in extract_feature
    pic_list = get_pic_list(db_path)
  File "/Users/star/workspace/python/Image-Practice/CBIR1/FeatureExtractor.py", line 18, in get_pic_list
    folders_1 = os.listdir(os.path.join(path, folder))  # 该数据集下所有类别
NotADirectoryError: [Errno 20] Not a directory: '/Users/star/workspace/python/Image-Practice/CBIR1/dataset/.DS_Store'
```

经过分析，是获取图片路径的时候，显示`.DS_Store`不存在，在终端中查看文件列表：
```python
star@StardeMacBook-Air dataset % ls -a
.			.DS_Store
..			101_ObjectCategories
```

发现确实多了一个隐藏文件，可能是讲完整数据集复制过来的时候，多出来的文件。本文件的功能是保存文件夹打开的位置，窗口大小，展现形式等信息。

使用`ls -a` 删除之后，正常运行



完成了三个基础功能的实现以及GUI的设计

## 2022-7-7

开始了解深度学习在CBIR方向的应用。

初步思路是模仿基础功能，用深度网络提取图片特征，建立特征数据库，在进行距离测量，进行排序索引。

### Problem 1

想下载pytorch自带的数据集进行神经网络的训练，发现错误：datasets.CIFAR100 datasets.CIFAR100

原因：指定的下载路径不合法

解决：换成相对路径表示



## 2022-7-8

### Problem 1

定义Dataset的时候报错，但是没有具体原因

```python
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/home/huan/zyx/CBIR/CBIR.ipynb Cell 6 in <cell line: 1>()
----> 1 mydataset = My_dataset('okapi')

/home/huan/zyx/CBIR/CBIR.ipynb Cell 6 in My_dataset.__init__(self, ty)
     12 image_path = os.path.join(path, ty + "/", image_path)
     13 print(image_path)
---> 14 self.img_paths.append(image_path)

File ~/anaconda3/envs/zyx/lib/python3.9/site-packages/torch/utils/data/dataset.py:83, in Dataset.__getattr__(self, attribute_name)
     81     return function
     82 else:
---> 83     raise AttributeError

AttributeError: 
```



查阅资料有人说可能是变量覆盖了关键字，由此推断是变量名称问题

经检查发现是前面定义的变量名称和后面使用的名称不一致。

### Problem 2

```python
RuntimeError: stack expects each tensor to be equal size, but got [295, 300, 3] at entry 0 and [300, 274, 3] at entry 1
```

dataloader里面图片大小不一致，需要进行预处理即可



### Problem 3

```python
IndexError: index 0 is out of bounds for axis 0 with size 0
```

索引越界，发现是数组开小了。一个变量初始化为0，之后就忘记进行修改成数据集的大小



### Problem 4

在画图时都是黑白图像

原因：发现在重写dataset时，用cv2读入图像的模式使用成了`cv2.BGR2GRAY`转成了灰度图像

解决：使用`cv2.BGR2RGB`



修改过后发现图像仍然不正常：<img src="https://s1.vika.cn/space/2022/07/09/1fa91d93bbaa4f12869daefd5e2f99c2" alt="image-20220709161004573" style="zoom:50%;" />







```python
path = "./dataset/101_ObjectCategories/okapi/image_0020.jpg"
img = cv2.cvtColor(cv2.imread(path), cv2.cv2.COLOR_BGR2RGB)
img = cv2.resize(img, (256, 256))
cv2.imshow("try", img)
```

尝试打印图像

发现报错：

```
Canceled future for execute_request message before replies were done
The Kernel crashed while executing code in the the current cell or a previous cell. Please review the code in the cell(s) to identify a possible cause of the failure. Click here for more info. View Jupyter log for further details.
```

不能通过cv2创建窗口，我推测是ipynb的原因

于是执行py文件测试，发现仍然抱错
```
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/home/huan/anaconda3/envs/zyx/lib/python3.9/site-packages/cv2/qt/plugins" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb.
```

原因：在服务器上没有图形界面

于是通过直接根据路径找到图片并画出进行验证，结果显示图片是正常的：

<img src="https://s1.vika.cn/space/2022/07/09/0d564c663c92411881d0eed6ce4ff419" alt="image-20220709162539084" style="zoom:50%;" />



所以直接将路径保存下来，所谓类的一个成员。



## 2022-7-9

撰写实验报告、制作PPT

微调深度学习模型

整理代码，优化架构

